language: ruby
rvm:
- 2.3.3
addons:
  code_climate:
    repo_token:
      secure: "TTJV+tkPbGVjCQDZNH5NEVr9HbVheUk0BZjAvJbYRtdIwAHzvVwbe5H24E8V1hq0E/5ECvZPN/mwRDXq5wJ9bT7vx3OasLVIDhlTcDExirgfFCeVQGd0lVyQYjSFMgK9j6iKr4LkHBj2uxBz26Q1UrT0KwXZ4zQ1RWFu8T2VAoqhO8UzDiR5j7ho34rTSqVFJgF7zFz3YPOr8jgK1vynrcNBFe82ElA8bjH+UkVB8p2bG5ib4i+vUqMSXPOBCo+qZ9OGEzmm2dNjRp8VNUBd0JwWrs/1HhGKeQQ7kbpiS8H6mYNJQtiGFgJWrGFjGFlUny09bWT1JRSuBtEZNotGHtZDidxkXHK3yys6ZOyrnAm6DWlYzK2mNzyp/FY+5aSKMnwB+eZ6YrKPPK0CjwXfoAUiOjK2VMJUXWrF5atjiXFrTVEnurDZW7h4vxJb7EDkvb+tuT9aPtxQoS6BrWUKTkl9rT1Xsp+NfBHuTHZMYyv05HsS7RgqXb7bOrPTAGwdam9xCafFOOrwQRF5OkJovZ13UobWzmgqscu4o39HmLXwWnKyC1QQ7FJ8NYLDQEQjQi7FjdCdmmYHhh/Y28brhSW8ar1EaZ1iPTuqsjdYzDqusjtRP5svpoV5RJ5Fes1pdoeXFv2YMaZVFc5RvmlRp8nlwyC9F9PhyjJWwK9f18w="
deploy:
  provider: rubygems
  api_key:
    secure: "BbwV2W8hxxLaYM1luukejgmgm0ODHFw3CNgQbK15D9tK1VoQqNxCxQzmCYgi2FG1MYYAQcTcVj7W+cd76REmKDEhxEyZUVmIQF+N16Zl2vR/UegsbXVd2Gpel2tyykO9ebSlkXHkwzcCMksIhwCdELJORbxGSqVxTl6FaNPS3bfylev5Cumk8SCKXEvg2BMH0BPFpXZSpijdVv5xTuzM0qQUx/thvEHcm9o9q1JEhM4XbEdffBSOM3BWM9yCoSshKO2GmCBNJOOp8JsDmRR3F+ynuTdV5b8AGSHd7oubh6OxZ26jusJXzIgxZ99hi4FTDRuvvyOcmKn6Of7DN6K3rBNoDmxf4E3OdujSJSRuDG2wbQz/1R7isBniabqxogeCgMEHabXP2QRN+SOkpLQthaFhr+ISMuH5ZRKRYcRBTJ6J/QGDPOxYe0JWJpwVhvE4jDK/UaGph6kt/DLrWR/SLXa2kPDlrWl2xe4z3SwuJRPhkfwHGVLIZSZR21bJ4ONnBYkXbFI8lTsLno7JA6SXPfTODRnJrlUWqV0xIwyWTsoxcgssMVUH2RgqiBHWxGIOJShVwoX5JEx3M5SRC7xvnwW5xF5+KHCxMKB5wXEfQRpZUBX+KKCBn5PP0U21QjHhUbYhy8k85QEaL+LWOX6BqZikBw/5QaZijNYvhCtZbQs="
  gem: fluent-plugin-ecs-filter
  on:
    repo: joshughes/fluent-plugin-ecs-filter
    branch: master
